DROP TABLE IF EXISTS book;

CREATE TABLE book (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  reader VARCHAR(250) DEFAULT NULL,
  isbn VARCHAR(250) DEFAULT NULL,
  title VARCHAR(250) DEFAULT NULL,
  author VARCHAR(250) DEFAULT NULL,
  description VARCHAR(250) DEFAULT NULL
);